In [1]:
import requests 
from lxml import html 
import csv
import pandas as pd

In [2]:
r = requests.get('https://www.basketball-reference.com/leagues/NBA_2017_per_game.html')
data = html.fromstring(r.text)

In [95]:
player = data.xpath("//tbody/tr/td[@data-stat='player']/a[@href]/text()")
position = data.xpath("//tbody/tr/td[@class='center ']/text()")
age = data.xpath("//tbody/tr/td[@data-stat='age']/text()")
team = data.xpath("//tbody/tr/td[@data-stat='team_id']/a[@href]/text()|//tbody/tr/td[@data-stat='team_id']/text()")
games = data.xpath("//tbody/tr/td[@data-stat='g']/text()")
games_started = data.xpath("//tbody/tr/td[@data-stat='gs']/text()")
mins_per_g = data.xpath("//tbody/tr/td[@data-stat='mp_per_g']/text()")
fg_per_g = data.xpath("//tbody/tr/td[@data-stat='fg_per_g']/text()")
fga_per_g = data.xpath("//tbody/tr/td[@data-stat='fga_per_g']/text()")
fg_pct = data.xpath("//tbody/tr/td[@data-stat='fg_pct']")
fg_pct = [i.text_content() for i in fg_pct]
fg3_per_g = data.xpath("//tbody/tr/td[@data-stat='fg3_per_g']/text()")
fg3a_per_g = data.xpath("//tbody/tr/td[@data-stat='fg3a_per_g']/text()")
fg3_pct = data.xpath("//tbody/tr/td[@data-stat='fg3_pct']")
fg3_pct = [i.text_content() for i in fg3_pct]
fg2_per_g = data.xpath("//tbody/tr/td[@data-stat='fg2_per_g']/text()")
fg2a_per_g = data.xpath("//tbody/tr/td[@data-stat='fg2a_per_g']/text()")
fg2_pct = data.xpath("//tbody/tr/td[@data-stat='fg2_pct']")
fg2_pct = [i.text_content() for i in fg2_pct]
efg_pct = data.xpath("//tbody/tr/td[@data-stat='efg_pct']")
efg_pct = [i.text_content() for i in efg_pct]
ft_per_g = data.xpath("//tbody/tr/td[@data-stat='ft_per_g']/text()")
fta_per_g = data.xpath("//tbody/tr/td[@data-stat='ft_per_g']/text()")
ft_pct = data.xpath("//tbody/tr/td[@data-stat='ft_pct']")
ft_pct = [i.text_content() for i in ft_pct]
orb_per_g = data.xpath("//tbody/tr/td[@data-stat='orb_per_g']/text()")
drb_per_g = data.xpath("//tbody/tr/td[@data-stat='drb_per_g']/text()")
trb_per_g = data.xpath("//tbody/tr/td[@data-stat='trb_per_g']/text()")
ast_per_g = data.xpath("//tbody/tr/td[@data-stat='ast_per_g']/text()")
stl_per_g = data.xpath("//tbody/tr/td[@data-stat='stl_per_g']/text()")
blk_per_g = data.xpath("//tbody/tr/td[@data-stat='blk_per_g']/text()")
tov_per_g = data.xpath("//tbody/tr/td[@data-stat='tov_per_g']/text()")
pf_per_g = data.xpath("//tbody/tr/td[@data-stat='pf_per_g']/text()")
pts_per_g = data.xpath("//tbody/tr/td[@data-stat='pts_per_g']/text()")

In [96]:
nba2017 = zip(player, 
              position, 
              age, 
              team, 
              games, 
              games_started, 
              mins_per_g, 
              fg_per_g, 
              fga_per_g, 
              fg_pct, 
              fg3_per_g, 
              fg3a_per_g, 
              fg3_pct, 
              fg2_per_g, 
              fg2a_per_g, 
              fg2_pct, 
              efg_pct, 
              ft_per_g, 
              fta_per_g, 
              ft_pct, 
              orb_per_g, 
              drb_per_g,
              trb_per_g,
              ast_per_g,
              stl_per_g,
              blk_per_g,
              tov_per_g,
              pf_per_g,
              pts_per_g)

df = pd.DataFrame(nba2017)

In [97]:
df = df.rename(columns = {0:'player', 
                          1:'position', 
                          2:'age', 
                          3:'team', 
                          4:'games', 
                          5:'games_started', 
                          6:'mins_per_g', 
                          7:'fg_per_g', 
                          8:'fga_per_g', 
                          9:'fg_pct', 
                          10:'fg3_per_g', 
                          11:'fg3a_per_g', 
                          12:'fg3_pct', 
                          13:'fg2_per_g', 
                          14:'fg2a_per_g', 
                          15:'fg2_pct', 
                          16:'efg_pct', 
                          17:'ft_per_g', 
                          18:'fta_per_g', 
                          19:'ft_pct', 
                          20:'orb_per_g', 
                          21:'drb_per_g',
                          22:'trb_per_g',
                          23:'ast_per_g',
                          24:'stl_per_g',
                          25:'blk_per_g',
                          26:'tov_per_g',
                          27:'pf_per_g',
                          28:'pts_per_g'})
df.head()

,player,position,age,team,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
0,Alex Abrines,SG,23,OKC,68,6,15.5,2.0,5.0,.393,...,.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,Quincy Acy,PF,26,TOT,38,1,14.7,1.8,4.5,.412,...,.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,Quincy Acy,PF,26,DAL,6,0,8.0,0.8,2.8,.294,...,.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,Quincy Acy,PF,26,BRK,32,1,15.9,2.0,4.8,.425,...,.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,Steven Adams,C,23,OKC,80,80,29.9,4.7,8.2,.571,...,.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 29 columns):
player           595 non-null object
position         595 non-null object
age              595 non-null object
team             595 non-null object
games            595 non-null object
games_started    595 non-null object
mins_per_g       595 non-null object
fg_per_g         595 non-null object
fga_per_g        595 non-null object
fg_pct           595 non-null object
fg3_per_g        595 non-null object
fg3a_per_g       595 non-null object
fg3_pct          595 non-null object
fg2_per_g        595 non-null object
fg2a_per_g       595 non-null object
fg2_pct          595 non-null object
efg_pct          595 non-null object
ft_per_g         595 non-null object
fta_per_g        595 non-null object
ft_pct           595 non-null object
orb_per_g        595 non-null object
drb_per_g        595 non-null object
trb_per_g        595 non-null object
ast_per_g        595 non-null object
stl_per_g        595 non-null object
blk_per_g        595 non-null object
tov_per_g        595 non-null object
pf_per_g         595 non-null object
pts_per_g        595 non-null object
dtypes: object(29)
memory usage: 134.9+ KB

In [107]:
df['age'] = pd.to_numeric(df['age'])
df['age'].fillna(0, inplace=True)

df['games'] = pd.to_numeric(df['games'])
df['games'].fillna(0, inplace=True)

df['games_started'] = pd.to_numeric(df['games_started'])
df['games_started'].fillna(0, inplace=True)

df['mins_per_g'] = pd.to_numeric(df['mins_per_g'])
df['mins_per_g'].fillna(0, inplace=True)

df['fg_per_g'] = pd.to_numeric(df['fg_per_g'])
df['fg_per_g'].fillna(0, inplace=True)

df['fga_per_g'] = pd.to_numeric(df['fga_per_g'])
df['fga_per_g'].fillna(0, inplace=True)

df['fg_pct'] = pd.to_numeric(df['fg_pct'])
df['fg_pct'].fillna(0, inplace=True)

df['fg3_per_g'] = pd.to_numeric(df['fg3_per_g'])
df['fg3_per_g'].fillna(0, inplace=True)

df['fg3a_per_g'] = pd.to_numeric(df['fg3a_per_g'])
df['fg3a_per_g'].fillna(0, inplace=True)

df['fg3_pct'] = pd.to_numeric(df['fg3_pct'])
df['fg3_pct'].fillna(0, inplace=True)

df['fg2_per_g'] = pd.to_numeric(df['fg2_per_g'])
df['fg2_per_g'].fillna(0, inplace=True)

df['fg2a_per_g'] = pd.to_numeric(df['fg2a_per_g'])
df['fg2a_per_g'].fillna(0, inplace=True)

df['fg2_pct'] = pd.to_numeric(df['fg2_pct'])
df['fg2_pct'].fillna(0, inplace=True)

df['efg_pct'] = pd.to_numeric(df['efg_pct'])
df['efg_pct'].fillna(0, inplace=True)

df['ft_per_g'] = pd.to_numeric(df['ft_per_g'])
df['ft_per_g'].fillna(0, inplace=True)

df['fta_per_g'] = pd.to_numeric(df['fta_per_g'])
df['fta_per_g'].fillna(0, inplace=True)

df['ft_pct'] = pd.to_numeric(df['ft_pct'])
df['ft_pct'].fillna(0, inplace=True)

df['orb_per_g'] = pd.to_numeric(df['orb_per_g'])
df['orb_per_g'].fillna(0, inplace=True)

df['drb_per_g'] = pd.to_numeric(df['drb_per_g'])
df['drb_per_g'].fillna(0, inplace=True)

df['trb_per_g'] = pd.to_numeric(df['trb_per_g'])
df['trb_per_g'].fillna(0, inplace=True)

df['ast_per_g'] = pd.to_numeric(df['ast_per_g'])
df['ast_per_g'].fillna(0, inplace=True)

df['stl_per_g'] = pd.to_numeric(df['stl_per_g'])
df['stl_per_g'].fillna(0, inplace=True)

df['blk_per_g'] = pd.to_numeric(df['blk_per_g'])
df['blk_per_g'].fillna(0, inplace=True)

df['tov_per_g'] = pd.to_numeric(df['tov_per_g'])
df['tov_per_g'].fillna(0, inplace=True)

df['pf_per_g'] = pd.to_numeric(df['pf_per_g'])
df['pf_per_g'].fillna(0, inplace=True)

df['pts_per_g'] = pd.to_numeric(df['pts_per_g'])
df['pts_per_g'].fillna(0, inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 595 entries, 0 to 594
Data columns (total 29 columns):
player           595 non-null object
position         595 non-null object
age              595 non-null int64
team             595 non-null object
games            595 non-null int64
games_started    595 non-null int64
mins_per_g       595 non-null float64
fg_per_g         595 non-null float64
fga_per_g        595 non-null float64
fg_pct           595 non-null float64
fg3_per_g        595 non-null float64
fg3a_per_g       595 non-null float64
fg3_pct          595 non-null float64
fg2_per_g        595 non-null float64
fg2a_per_g       595 non-null float64
fg2_pct          595 non-null float64
efg_pct          595 non-null float64
ft_per_g         595 non-null float64
fta_per_g        595 non-null float64
ft_pct           595 non-null float64
orb_per_g        595 non-null float64
drb_per_g        595 non-null float64
trb_per_g        595 non-null float64
ast_per_g        595 non-null float64
stl_per_g        595 non-null float64
blk_per_g        595 non-null float64
tov_per_g        595 non-null float64
pf_per_g         595 non-null float64
pts_per_g        595 non-null float64
dtypes: float64(23), int64(3), object(3)
memory usage: 134.9+ KB

In [108]:
df.head()

,player,position,age,team,games,games_started,mins_per_g,fg_per_g,fga_per_g,fg_pct,...,ft_pct,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g
0,Alex Abrines,SG,23,OKC,68,6,15.5,2.0,5.0,0.393,...,0.898,0.3,1.0,1.3,0.6,0.5,0.1,0.5,1.7,6.0
1,Quincy Acy,PF,26,TOT,38,1,14.7,1.8,4.5,0.412,...,0.750,0.5,2.5,3.0,0.5,0.4,0.4,0.6,1.8,5.8
2,Quincy Acy,PF,26,DAL,6,0,8.0,0.8,2.8,0.294,...,0.667,0.3,1.0,1.3,0.0,0.0,0.0,0.3,1.5,2.2
3,Quincy Acy,PF,26,BRK,32,1,15.9,2.0,4.8,0.425,...,0.754,0.6,2.8,3.3,0.6,0.4,0.5,0.6,1.8,6.5
4,Steven Adams,C,23,OKC,80,80,29.9,4.7,8.2,0.571,...,0.611,3.5,4.2,7.7,1.1,1.1,1.0,1.8,2.4,11.3

In [113]:
pd.DataFrame.to_csv(df, 'data/nba.csv')